
# Learning Outcomes by Subject

When students complete this module, they will be able to:

## Science/Data Science (?)

### Overarching LOs - to be applied at all tiers

- Understand how data science can be used to create environmental solutions for communities
- Place data science questions in context (ecological, environmental, community solution, etc)
- Understand complexities and limitations of data
- Evaluate drawbacks/benefits of tools like EJScreen
- Interpret results in context (ecological, environmental, community solution, etc)

### Tier 1 (Intro level)

*Prerequisite Knowledge: None!*

- Explain how environmental indices can affect their community
- Evaluate the differences in the tools (EJScreen vs CEJST vs state-based(?) tools)
- And the benefits/drawbacks of the tools and how underlying data influences results (e.g., EJScreen uses census data - that is biased)
- Evaluate the positives and negatives of abstracting a place to one number
- Understand how weighting can impact results
- Question policy-makers and land managers on environmental justice issues
- Collaboratively develop action plans to move forward from their findings (wording of this sentence?) 
- Tier 2 (Mid level)

*Prerequisite Knowledge: Basic introduction to data science and statistical analyses, e.g. *

- Access data through R
- Execute pre-written example code and interpret the results
- Construct and modify R code to test hypotheses
- Choose a place and tell a story about why it is identified as an EJ place. What is missing? Is there a place that you thought would show up in EJ screen but does not? What data gap makes that happen?

### Tier 3 (Upper Division)

*Prerequisite Knowledge:*

- Student-driven project initiatives (SMART principles)
- Formulate a testable question
- Justify why this question is interesting with appropriate background information
- Create a justified hypothesis
- Obtain data from public sources (like EJ screen)
- Process raw data into usable formats
- Analyze data with appropriate statistical methods to answer the question
- Visualize data 
- Contextualize results in broader context ((ecological, environmental, community solution, etc)
- Communicate results through - e.g. a paper, poster, flash talk, other format

- quantitative models to address scientific questions?
- Testable question
- Placed in the context
- Obtaining, cleaning, transforming, and processing raw data into usable formats?
- Apply a range of statistical methods for inference and prediction…
- Build data science products that can be used by a broad audience - or can be transferable to other broader contexts

## Social Science:

Geared towards students who
- Never have made a map before

### Tier 1: 

- Explain how environmental data science tools reflect our understandings of race and can both perpetuate and challenge racism 
- Interpret maps
- Navigate the EJScreen tool and/or other similar tools to answer relevant, student-generated research questions about environmental (in)justice
- Understand how these can benefit their own community and neighborhood 

### Tier 2:

- Involve in ethnographic studies 
- Be able to infer data with a broad socio-economic context
- Visualization of data using programming languages such as R
- Maybe tie-up with different environmental law firms to get a hands-on learning experience by interning/volunteering!

### Tier 3: 

- Placement opportunities for students interested in continuing this field of science 
- Introduce public health implications of the data and research?
- Discuss data ethics? 
