
# Assessment

## Student assessment (Jazzmine): 

### Tier 1

- Exam questions
- Give a benefit and drawback of using one environmental index to describe an area. Possible answers: Benefits: relatively low-cost, easy, utilized pre-existing resources. Drawbacks: May or may not be an accurate representation of the health, no way to check it. A lot depends on the weighting, quality of the data going in, etc.
- Suppose you look at two different indices and get very different numbers (e.g., one assigns an area 50/100, the other assigns 75/100). Give two possible reasons for these differences. Possible answers: Includes different raw data, different weighting, includes different variables.
- Guided questions for any pre reading
- Guided worksheet for students throughout module
- Low-pressure quiz questions
- Art project-draw a scene from your neighborhood. Include the three biggest things you see as impacting the environmental health of your neighborhood. Are - all three on the index? If not, how hard would it be to collect data to include them? Could it be collected nationwide?

### Tier 2

- Individual or collaborative project
- Group projects encouraging working together 

### Tier 3

- Build your own case study and come up with data analysis to present to the class
- Several principles or programming functions demonstrated successfully (e.g., data wrangling / specific R functions)
- Apply to your own research question (if graduate student)

## Assessment & evolution of the module itself 

- Assessment & evolution of the module itself (Nate, Ellen, ):
- Survey of students pre- and post- course (self efficacy, excitement for data science, data science is relevant to me, belonging indices, etc)
- Survey of faculty/instructors that are actually teaching the course (self-efficacy)
- Incorporate feedback into further development of the module

**Online repository for student submissions, so students can see what others are working on across the country**
